package com.alexit.justrecipes.presentation.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
data class CustomDimension(
    val heightTitlePanel: Dp,
    val heightBottomMenu: Dp,
    val thicknessDividerBottomMenu: Dp,
    val heightDividerBottomMenu: Dp,
    val heightTopBorderButtonSelected: Dp,
    val paddingTextTitlePanel: Dp,
    val heightInputTextField: Dp,
    val widthInputTextField: Dp,
    val widthShowedTextField: Dp,
    val widthShowedText: Dp,
    val widthInputtedIngredientWeight: Dp,
    val heightInputtedIngredientWeight: Dp,
    val paddingFieldInput: Dp,
    val contentPaddingField: Dp,
    val radiusCornerField: Dp,
    val borderThickness: Dp,
    val sizeIcon1: Dp,
    val sizeIcon2: Dp,
    val sizeIcon3: Dp,
    val heightDialog: Dp,
    val widthDialog: Dp,
    val heightPopup: Dp,
    val widthPopup: Dp,
    val heightNewIngredientDialog: Dp,
    val widthNewIngredientDialog: Dp,
    val sizeCircleLoader: Dp,
    val widthRecipeCard: Dp,
    val heightRecipeCard: Dp,
    val gap1: Dp,
    val widthNameRecipeCard: Dp,
    val heightNameRecipeCard: Dp,
    val sizeImageRecipeCard: Dp,
    val widthIconInfoRecipeCard: Dp,
    val innerPaddingCard: Dp,
    val scrollBarThickness: Dp,
    val scrollBarMinLength: Dp,
    val sizeImageRecipe: Dp,
    val widthIngredientNameInRecipe: Dp,
    val widthIngredientNameInRequest: Dp,
    val heightSelectorDish: Dp,
    val widthSelectorDish: Dp,
    val heighButtonTitlePanel: Dp
)

val themeDimension = CustomDimension(
    heightTitlePanel = 88.dp,
    heightBottomMenu = 62.dp,
    thicknessDividerBottomMenu = 2.dp,
    heightDividerBottomMenu = 54.dp,
    heightTopBorderButtonSelected = 6.dp,
    paddingTextTitlePanel = 11.dp,
    heightInputTextField = 48.dp,
    widthInputTextField = 330.dp,
    widthShowedText = 170.dp,
    widthShowedTextField = 292.dp,
    widthInputtedIngredientWeight = 70.dp,
    heightInputtedIngredientWeight = 30.dp,
    paddingFieldInput = 12.dp,
    contentPaddingField = 10.dp,
    radiusCornerField = 12.dp,
    borderThickness = 1.dp,
    sizeIcon1 = 32.dp,
    sizeIcon2 = 24.dp,
    sizeIcon3 = 28.dp,
    heightDialog = 200.dp,
    widthDialog = 300.dp,
    heightPopup = 150.dp,
    widthPopup = 330.dp,
    heightNewIngredientDialog = 500.dp,
    widthNewIngredientDialog = 300.dp,
    sizeCircleLoader = 50.dp,
    widthRecipeCard = 330.dp,
    heightRecipeCard = 135.dp,
    gap1 = 4.dp,
    widthNameRecipeCard = 230.dp,
    heightNameRecipeCard = 95.dp,
    sizeImageRecipeCard = 80.dp,
    widthIconInfoRecipeCard = 75.dp,
    innerPaddingCard = 24.dp,
    scrollBarThickness = 4.dp,
    scrollBarMinLength = 44.dp,
    sizeImageRecipe = 330.dp,
    widthIngredientNameInRecipe = 250.dp,
    widthIngredientNameInRequest = 300.dp,
    heightSelectorDish = 48.dp,
    widthSelectorDish = 330.dp,
    heighButtonTitlePanel = 34.dp
)

val LocalCustomDimension = staticCompositionLocalOf {
    themeDimension
}
